// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ChartJS
{
	public partial class LaunchController : UIViewController
	{
		public LaunchController (IntPtr handle) : base (handle)
		{
		}
	}
}
