// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;
using WebKit;
using cdeutsch;
using System.IO;

namespace ChartJS
{
    public partial class BarController : UIViewController
    {
        public BarController(IntPtr handle) : base(handle)
        {
        }
       
        public override void ViewDidLoad()
        {
            //base.ViewDidLoad();
            int[] myNum = new int[]{ 10, 20, 30, 40,50};
            UIWebView webView = new UIWebView();
            string fileName = "BarChart.html";
            string localHtmlUrl = Path.Combine(NSBundle.MainBundle.BundlePath, fileName);
            webView.LoadRequest(new NSUrlRequest(new NSUrl(localHtmlUrl, false)));
            webView.BackgroundColor = UIColor.Yellow;
            webView.Frame = new CGRect(20, 80, UIScreen.MainScreen.Bounds.Width - 40, UIScreen.MainScreen.Bounds.Height - 100);
            Add(webView);
            webView.LoadFinished += (object sender, EventArgs e) =>
            {
                //Fire event from the controller which will be listened by the html page
                webView.FireEvent("doBrowserStuff", new
                {
                    Type="horizontalBar",
                    ChartData = new int[] { 60, 20, 30, 40, 50 }
                });
            };


        }
    }

}

