// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace ChartJS
{
	public partial class LineController : UIViewController
	{
		public LineController (IntPtr handle) : base (handle)
		{
		}
        public override void ViewDidLoad()
        {
            //base.ViewDidLoad();
            UIWebView webView = new UIWebView();
            string filePath = NSBundle.MainBundle.PathForResource("web/html/LineChart", "html");
            Console.Write("worked");
            string htmlStr = System.IO.File.ReadAllText(filePath);
            webView.LoadHtmlString(htmlStr, NSUrl.FromString(""));
            webView.BackgroundColor = UIColor.Yellow;
            webView.Frame = new CGRect(20, 80, UIScreen.MainScreen.Bounds.Width - 40, UIScreen.MainScreen.Bounds.Height - 100);
            Add(webView);
        }
    }
}
